### ISSUE TITLE
deduceEnvironment seems to require convertYamlToJava

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aot#31]
## Sample App

Create a Micronaut application with a configuration properties:

```java
package example.micronaut;

import io.micronaut.context.annotation.ConfigurationProperties;
import io.micronaut.context.annotation.EachProperty;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import javax.validation.constraints.NotBlank;
import java.util.List;

@ConfigurationProperties("hogwarts")
public class Hogwarts {

    @NonNull
    @NotBlank
    private String headmaster;

    @Nullable
    private List<Student> students;

    @Nullable
    public List<Student> getStudents() {
        return students;
    }

    public void setStudents(@Nullable List<Student> students) {
        this.students = students;
    }

    @NonNull
    public String getHeadmaster() {
        return headmaster;
    }

    public void setHeadmaster(@NonNull String headmaster) {
        this.headmaster = headmaster;
    }

    @EachProperty("students")
    public static class Student {
        @NonNull
        @NotBlank
        private String firstName;

        @NonNull
        @NotBlank
        private String lastName;

        @NonNull
        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(@NonNull String firstName) {
            this.firstName = firstName;
        }

        @NonNull
        public String getLastName() {
            return lastName;
        }

        public void setLastName(@NonNull String lastName) {
            this.lastName = lastName;
        }
    }

}
```

and a Controller

```java
package example.micronaut;

import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

@Controller("/hogwarts")
class HogwartsController {

    private final Hogwarts hogwarts;

    HogwartsController(Hogwarts hogwarts) {
        this.hogwarts = hogwarts;
    }

    @Get
    Hogwarts index() {
        return hogwarts;
    }
}
```

Three configuration files: 

`src/main/resources/application.yml`

```yaml
micronaut:
  application:
    name: micronautguide
---
hogwarts:
  headmaster: Albus Dumbledore
```

`src/main/resources/application-gryffindor.yml`:

```yaml
hogwarts:
  students:
    harry:
      first-name: 'Harry'
      last-name: 'Potter'
    ron:
      first-name: 'Ron'
      last-name: 'Weasley'
    hermione:
      first-name: 'Hermione'
      last-name: 'Granger'
```

`src/main/resources/application-slytherin.yml`:

```yaml
hogwarts:
  students:
    gregory:
      first-name: 'Gregory'
      last-name: 'Goyle'
    vicent:
      first-name: 'Vicent'
      last-name: 'Crabbe'
    draco:
      first-name: 'Draco'
      last-name: 'Malfoy'
```

Modify the build and apply AOT, application and shadow Gradle plugins:

```groovy
plugins {
    id("io.micronaut.application") version "3.1.0-M1"
    id("com.github.johnrengelman.shadow") version "7.1.0"
    id("io.micronaut.aot") version "3.1.0-M1"
}

...

micronaut {
    ...
    aot {
        version = "1.0.0-M3"
        deduceEnvironment = true
    }
}
```

### Steps to reproduce

Open a new terminal:

```bash
-- verify HOGWARTS_HEADMASTER is not set
echo $HOGWARTS_HEADMASTER
```

Set `MICRONAUT_ENVIRONMENTS` to `gryffindor`

```
export MICRONAUT_ENVIRONMENTS=gryffindor
```

# build regular FAT JAR and Optimized fat JAR

```
rm -rf build
./gradlew build
./gradlew optimizedJitJarAll
```

Set a different environment and environment variable than the one used at build time:

```
export MICRONAUT_ENVIRONMENTS=slytherin
export HOGWARTS_HEADMASTER=Snape
```

If I execute the regular FAT Jar I get an output using the Micronaut environment and  environment variable use at runtime:

```
java -jar build/libs/micronautguide-0.1-all.jar
 % curl localhost:8080/hogwarts
{"headmaster":"Snape","students":[{"firstName":"Vicent","lastName":"Crabbe"},{"firstName":"Draco","lastName":"Malfoy"},{"firstName":"Gregory","lastName":"Goyle"}]}%           
```

However, If I execute the optimized FAT Jar I get the runtime output as well. 

Only, If I set `convertYamlToJava` and `optimizeServiceLoading` to true as well.

```yaml
    aot {
        version = "1.0.0-M3"
        optimizeServiceLoading = true
        convertYamlToJava = true
        deduceEnvironment = true
   }
```

I get: 

```java
{"headmaster":"Albus Dumbledore","students":[{"firstName":"Harry","lastName":"Potter"},{"firstName":"Ron","lastName":"Weasley"},{"firstName":"Hermione","lastName":"Granger"}]}%                                                                sdelamo@ig11 ~ % 
```

Is `convertYamlToJava` required to use `deduceEnvironment` If yes I think the build should fail as it fails when you use `convertYamlToJava` without `optimizedServiceLoading`
