### ISSUE TITLE
Using placeholder resolution in convertYamlToJava

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-aot#83]
### Feature description

It seems it is not possible to use placeholder resolutions like this when converting YAML to Java:

```yaml
micronaut:
  application:
    name: ${APP_NAME:default-value}
```

For me it seems like standard use case also documented in official manual for using secrets in configuration.
